const homeStyles = {
  container: {
    flex: 1,
    backgroundColor: '#f5f6fa',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  clockBadge: {
    position: 'absolute',
    top: 50,
    right: 50,
    borderWidth: 1,
    borderColor: '#d0d5dd',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  settingsButton: {
    position: 'absolute',
    top: 110,
    right: 50,
    zIndex: 2,
    borderWidth: 1,
    borderColor: '#d0d5dd',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    paddingVertical: 15,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  settingsButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#101828',
  },
  clockText: {
    fontFamily: 'monospace',
    fontSize: 14,
    fontWeight: '700',
    color: '#101828',
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    marginBottom: 18,
  },
  bonCount: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    color: '#334155',
  },
  errorMessage: {
    color: '#b91c1c',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
  },
  inputContainer: {
    width: '100%',
    maxWidth: 360,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d0d5dd',
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 18,
  },
  input: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 18,
    textAlign: 'right',
  },
  currency: {
    fontSize: 18,
    fontWeight: '600',
    color: '#344054',
    paddingRight: 14,
  },
  grid: {
    width: '100%',
    maxWidth: 360,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 16,
  },
  button: {
    width: '30%',
    minWidth: 90,
    backgroundColor: '#101828',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    overflow: 'hidden',
  },
  buttonText: {
    color: '#fff',
    fontSize: 30,
    fontWeight: '700',
  },
  buttonDeleteLast: {
    backgroundColor: '#475467',
  },
  buttonDeleteLastText: {
    fontSize: 22,
  },
  generateButton: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#09b14a',
    borderRadius: 10,
    paddingVertical: 50,
    paddingHorizontal: 30,
    alignItems: 'center',
    overflow: 'hidden',
  },
  clearButton: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#c1121f',
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 30,
    alignItems: 'center',
    marginTop: 20,
    overflow: 'hidden',
  },
  clearButtonText: {
    color: '#fff',
    fontSize: 30,
    fontWeight: '600',
  },
};

export default homeStyles;
