const resultStyles = {
  generatedFieldView: {
    width: '100%',
    maxWidth: 360,
    marginTop: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#09b14a',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  generatedFieldTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#067647',
    marginBottom: 20,
  },
  generatedLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#067647',
    marginTop: 20,
    marginBottom: 6,
  },
  generatedValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#101828',
  },
  signaturePresentText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#067647',
    marginTop: 8,
  },
  signatureMissingText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#b42318',
    marginTop: 8,
  },
  signatureValueText: {
    fontSize: 11,
    color: '#475467',
    marginTop: 2,
    marginBottom: 4,
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  backButton: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#101828',
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginTop: 16,
    overflow: 'hidden',
  },
  backButtonText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
  },
};

export default resultStyles;
